// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQy51_tmlps3_g-_MoqfcGYhTa0BsRfFY',
    appId: '1:788124595860:web:b0a6c81b3b3a13171de681',
    messagingSenderId: '788124595860',
    projectId: 'pixmania-182c7',
    authDomain: 'pixmania-182c7.firebaseapp.com',
    storageBucket: 'pixmania-182c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bNpQQdFBC6K9jIvM583v6RXQa3Gk2fc',
    appId: '1:788124595860:android:dc1a87a1f2c7901c1de681',
    messagingSenderId: '788124595860',
    projectId: 'pixmania-182c7',
    storageBucket: 'pixmania-182c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBESA49lKVgl-0_6iLWZvvJ_09uLKS_E34',
    appId: '1:788124595860:ios:cccd4da51c4b63311de681',
    messagingSenderId: '788124595860',
    projectId: 'pixmania-182c7',
    storageBucket: 'pixmania-182c7.appspot.com',
    iosClientId: '788124595860-npp762pk9tr09hg4j8ajdqoqou95ecun.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixmania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBESA49lKVgl-0_6iLWZvvJ_09uLKS_E34',
    appId: '1:788124595860:ios:cccd4da51c4b63311de681',
    messagingSenderId: '788124595860',
    projectId: 'pixmania-182c7',
    storageBucket: 'pixmania-182c7.appspot.com',
    iosClientId: '788124595860-npp762pk9tr09hg4j8ajdqoqou95ecun.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixmania',
  );
}
